
# -*- makefile -*-
# Do not edit this file.
# This file will be overwritten by the project setup script.

RAW_SIMICS_BASE=/home/carlos27/Simics/simics-6.0.128
RAW_SIMICS_MODEL_BUILDER=/home/carlos27/Simics/simics-6.0.128
RAW_EML_PACKAGE=
RAW_DODOC_PKG=/home/carlos27/Simics/simics-6.0.128

RAW_SIMICS_PACKAGE_LIST=/home/carlos27/Simics/simics-6.0.128/.package-list

INCLUDE_PATHS = /home/carlos27/Simics/simics-6.0.128/src/include
CXX_INCLUDE_PATHS = /home/carlos27/Simics/simics-6.0.128/linux64/api
DML_INCLUDE_PATHS = /home/carlos27/Simics/simics-6.0.128/linux64/bin/dml/api
HOST_TYPE = linux64
